@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb2huQGV4YW1wbGUuY29tIiwiaWF0IjoxNzU3MTY4MTA0LCJleHAiOjE3NTc2ODY1MDR9.DDC6RZmHnj2ngaZkQYaRDIVxF8Z8X5xpxmHUukauSFA
@BASE_URL = http://localhost:3002/api/cart


### Add new item to cart
POST {{BASE_URL}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "productId": 13,
  "qty": 15
}


### Update cart Item
PATCH {{BASE_URL}}/1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "qty": 50
}


### Delete cart Item
DELETE {{BASE_URL}}/1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}


### Get cart
GET {{BASE_URL}}/cart
Authorization: Bearer {{TOKEN}}