name: Auth Service CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [service-auth]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Start dependency services
        run: docker compose up -d
        working-directory: ${{ github.workspace }}

      - name: Wait for services
        run: sleep 20

      - name: Build Docker image
        run: docker build --target builder -t ${{ matrix.service }}-ci:latest ./${{ matrix.service }}

      # Uncomment if you want tests
      # - name: Run tests
      #   run: docker run --rm --network host ${{ matrix.service }}-ci:latest npm test

      - name: Stop dependency services
        run: docker compose down
        working-directory: ${{ github.workspace }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy on VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd ~/services/service-auth
            git fetch --all
            git reset --hard origin/main
            git clean -fd
            docker-compose -f docker-compose.auth.yml down --remove-orphans
            docker-compose -f docker-compose.auth.yml build --no-cache
            docker-compose -f docker-compose.auth.yml up -d
          EOF
