name: Deploy Auth Service to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Deploy service-auth
        working-directory: ./service-auth
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_KEY }}
        run: |
          railway up --detach --environment CI
