name: Deploy Auth Service to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install Railway CLI
      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      # 4️⃣ Link Railway project non-interactively
      - name: Link Railway project
        working-directory: ./service-auth
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_KEY }}
        run: |
          echo "y" | railway link --project 2fc979e6-3249-4628-9a6b-f95380490903 --environment CI

      # 5️⃣ Deploy service-auth
      - name: Deploy service-auth
        working-directory: ./service-auth
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_KEY }}
        run: railway up --detach
